name: Commitlint with Bun

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: |
          bun install --dev @commitlint/cli @commitlint/config-conventional
      
      - name: Create commitlint config
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
      
      - name: Lint branch commits
        if: github.event_name == 'push'
        run: |
          # Récupérer le SHA du premier commit de cette branche (où elle diverge de origin/main)
          FIRST_COMMIT=$(git merge-base origin/main HEAD)
          bunx commitlint --from $FIRST_COMMIT --to HEAD --verbose
      
      - name: Lint PR branch commits
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose